language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer install

script: ./vendor/bin/phpunit -c ./phpunit.xml.dist

script:
 - ./vender/bin/phpunit -c ./phpunit.xml.dist
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v